services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - shared-data:/app/shared
      - ./external/tree-sitter-repos:/app/external/tree-sitter-repos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/capabilities"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9000/api
    depends_on:
      - backend
    volumes:
      - shared-data:/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  shared-data: 